# Generated by Django 6.0.4 on 2026-04-16 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyQueueSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_date', models.DateField(db_index=True)),
                ('is_active', models.BooleanField(default=True)),
                ('start_token_number', models.PositiveIntegerField(default=1)),
                ('last_issued_token_number', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-queue_date', '-created_at'],
            },
        ),
    ]
