# Generated by Django 6.0.4 on 2026-04-16 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('queue', '0001_initial'),
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyqueuesession',
            name='current_visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_sessions', to='visits.visit'),
        ),
        migrations.AddConstraint(
            model_name='dailyqueuesession',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('queue_date',), name='unique_active_queue_session_per_date'),
        ),
    ]
