# Generated by Django 6.0.4 on 2026-04-16 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_name', models.CharField(default='Queue Management MVP', max_length=255)),
                ('queue_prefix', models.CharField(blank=True, max_length=20)),
                ('public_display_show_patient_name', models.BooleanField(default=False)),
                ('urgent_cases_jump_queue', models.BooleanField(default=True)),
                ('daily_reset_mode', models.CharField(choices=[('manual', 'Manual'), ('auto', 'Auto')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'App Setting',
                'verbose_name_plural': 'App Settings',
            },
        ),
    ]
