# Generated by Django 6.0.4 on 2026-04-16 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('queue', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('with_doctor', 'With Doctor'), ('completed', 'Completed'), ('skipped', 'Skipped'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], db_index=True, default='waiting', max_length=20)),
                ('priority_level', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent')], db_index=True, default='normal', max_length=20)),
                ('short_note', models.CharField(blank=True, max_length=255)),
                ('doctor_note', models.TextField(blank=True)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_visits', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='patients.patient')),
                ('queue_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='queue.dailyqueuesession')),
            ],
            options={
                'ordering': ['token_number'],
                'constraints': [models.UniqueConstraint(fields=('queue_session', 'token_number'), name='unique_token_per_queue_session'), models.UniqueConstraint(condition=models.Q(('status', 'with_doctor')), fields=('queue_session',), name='unique_with_doctor_per_session')],
            },
        ),
    ]
